[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "Cython>=0.28.5",
    "numpy"
]

[tool.black]
line-length = 79

[tool.cibuildwheel]
manylinux-i686-image = "manylinux2010"
